language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura -Dgpg.skip=true"

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

after_success:
  - bash <(curl -s https://codecov.io/bash)